### ISSUE TITLE
Change the color of the leftmost vertical bar (`.cell.selected::before`) in different vim-modes

### ISSUE THREAD

**Issue by joelostblom** [lambdalisue/jupyter-vim-binding#117]
### Summary

The following in `custom.css` work as expected and change the color of the leftmost vertical bar when in jupyter and vim mode:

```css
/* Change color of the leftmost vertical bar in jupyter mode */
.cell.selected::before {
    background-color: steelblue;
}
/* Change color of the leftmost vertical bar in vim mode */
.edit_mode .cell.selected::before {
    background-color: lightgreen;
}
```

However, I cannot figure out out to change the color to differentiate between vim normal and vim insert mode. I would expect this to be 

```css
.edit_mode .cell.selected::before .CodeMirror-focused:not(.cm-fat-cursor) {
    background-color: black;
}
```
But it is not working. I also tried adding `background-color: black !important;` without effect.

This is unexpected to me, since I can use the following to change the background color of the cell without any problems:

```css
/* Jupyter cell is in normal mode when code mirror */
.edit_mode .cell.selected .CodeMirror-focused.cm-fat-cursor {
  background-color: #f7f7f7 !important;
}
/* Jupyter cell is in insert mode when code mirror */
.edit_mode .cell.selected .CodeMirror-focused:not(.cm-fat-cursor) {
  background-color: #ffffff !important;
}
```

Any ideas of how to change the color of the leftmost bar between vim normal and insert mode?

### Environment

- [x] Operating system : Antegros (arch) with i3. Kernel 4.13.3-1-ARCH 64bit)
- [x] Web browser : Firefox 55.0.3
- [x] Version or revision of Jupyter Notebook : 5.0.0
- [x] Revision of jupyter-vim-binding : 7f1a585

**Comment by lambdalisue** [comment]
> In CSS, ::before creates a pseudo-element that is the first child of the selected element.

https://developer.mozilla.org/en-US/docs/Web/CSS/::before

So `.edit_mode .cell.selected::before .CodeMirror-focused:not(.cm-fat-cursor)` points wrong one while `::before` insert a pseudo-element.

Try `.edit_mode .cell.selected .CodeMirror-focused:not(.cm-fat-cursor)` (I don't have a jupyter environment right now so I couldn't test it)

**Comment by joelostblom** [comment]
Thanks for your reply @lambdalisue.

I tried this

```css
.edit_mode .cell.selected .CodeMirror-focused:not(.cm-fat-cursor) {
    background-color: black !important;
}
```

But it only changes the color of the cell background when editing, not the vertical bar to the left of the cell.
