### ISSUE TITLE
how can I change the color of cursor when I in the command mode?

### ISSUE THREAD

**Issue by PKUFlyingPig** [lambdalisue/jupyter-vim-binding#149]
<img width="299" alt="image" src="https://user-images.githubusercontent.com/60659728/75638195-c08ade00-5c65-11ea-93d0-8112c6a06360.png">

**Comment by foxale** [comment]
It looks like the color is predefined in _[codemirror.css](https://codemirror.net/lib/codemirror.css)_ 

```css
.cm-fat-cursor .CodeMirror-cursor {
  width: auto;
  border: 0 !important;
  background: #7e7;
}
.cm-fat-cursor div.CodeMirror-cursors {
  z-index: 1;
}
.cm-fat-cursor-mark {
  background-color: rgba(20, 255, 20, 0.5);
  -webkit-animation: blink 1.06s steps(1) infinite;
  -moz-animation: blink 1.06s steps(1) infinite;
  animation: blink 1.06s steps(1) infinite;
}
.cm-animate-fat-cursor {
  width: auto;
  border: 0;
  -webkit-animation: blink 1.06s steps(1) infinite;
  -moz-animation: blink 1.06s steps(1) infinite;
  animation: blink 1.06s steps(1) infinite;
  background-color: #7e7;
}
```
